exports.referrenceKey = {
  "https://www.google.com/": "Google Search",
  "https://www.facebook.com/": "Facebook",
  "https://www.youtube.com/": "YouTube",
  "https://twitter.com/": "Twitter (X)",
  "https://wa.me/": "WhatsApp",
  "https://l.instagram.com/": "Instagram",
  "https://www.reddit.com/": "Reddit",
  "https://www.linkedin.com/": "LinkedIn",
  "https://www.bing.com/": "Bing Search",
  "https://www.tiktok.com/": "TikTok",
  "https://mail.google.com/": "Gmail",
  "https://outlook.live.com/": "Outlook",
  "https://news.google.com/": "Google News",
  "https://www.amazon.com/": "Amazon",
  "https://www.ebay.com/": "eBay",
  "https://www.yahoo.com/": "Yahoo",
  "https://www.quora.com/": "Quora",
  "https://www.medium.com/": "Medium",
  "https://www.pinterest.com/": "Pinterest",
  "https://www.stackoverflow.com/": "Stack Overflow",
  "https://www.nytimes.com/": "New York Times",
  "https://www.cnn.com/": "CNN",
  "https://www.bbc.com/": "BBC",
  "https://www.naver.com/": "Naver (Korea)",
  "https://www.yandex.ru/": "Yandex (Russia)",
  "https://www.t.co/": "Twitter Shortener",
  "https://bit.ly/": "Bitly",
  "https://linktr.ee/": "Linktree",
  "https://linkin.bio/": "Linkin.bio",
  "https://shopee.com/": "Shopee",
  "https://www.alibaba.com/": "Alibaba",
  "https://www.snapchat.com/": "Snapchat"
}
